apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: two-port-app
  name: two-port-app
spec:
  containers:
  - image: cmwylie19/two-port-app
    name: two-port-app
    resources: {}
    ports:
    - name: http
      containerPort: 8081
    - name: http2
      containerPort: 8082
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: two-port-app
  name: two-port-app
spec:
  ports:
  - name: port-1
    port: 8081
    protocol: TCP
    targetPort: 8081
  - name: port-2
    port: 8082
    protocol: TCP
    targetPort: 8082
  selector:
    run: two-port-app
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    run: port-one
  name: port-one
spec:
  port:
    targetPort: port-1
  to:
    kind: Service
    name: two-port-app
    weight: null
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    run: port-two
  name: port-two
spec:
  port:
    targetPort: port-2
  to:
    kind: Service
    name: two-port-app
    weight: null
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  creationTimestamp: null
  name: two-port-app
spec:
  ingressClassName: openshift-default
  rules:
  - http:
      paths:
      - backend:
          service:
            name: two-port-app
            port:
              number: 8081
        path: /
        pathType: Prefix
  - http:
      paths:
      - backend:
          service:
            name: two-port-app
            port:
              number: 8082
        path: /
        pathType: Prefix
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  creationTimestamp: null
  name: test
spec:
  rules:
  - host: port-one.apps.tetrate-mp-cp.kni.syseng.devcluster.openshift.com
    http:
      paths:
      - backend:
          service:
            name: two-port-app
            port:
              number: 8081
        path: /
        pathType: Prefix
  - host: port-two.apps.tetrate-mp-cp.kni.syseng.devcluster.openshift.com
    http:
      paths:
      - backend:
          service:
            name: two-port-app
            port:
              number: 8082
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - port-one.apps.tetrate-mp-cp.kni.syseng.devcluster.openshift.com
    secretName: port-one-tls
  - hosts:
    - port-two.apps.tetrate-mp-cp.kni.syseng.devcluster.openshift.com
    secretName: port-two-tls